#!/usr/bin/env bash

# =============================================================================
# Script:      fail2ban.sh
# Description: Installs and configures fail2ban with extended jails on Arch
#              Linux, targeting:
#                - SSH brute-force protection (standard + aggressive)
#                - nginx HTTP abuse protection
#                - Recidive jail for repeat offenders
#                - nftables integration (Arch default firewall)
#
# Author:      Bruno Schmid @brulliant
# LinkedIn:    https://www.linkedin.com/in/schmidbruno/
#
# Usage:       sudo ./fail2ban.sh [-p SSH_PORT] [-h]
#
# Requirements:
#   - Arch Linux with pacman
#   - Root privileges
#   - nftables installed and running (Arch default)
#
# What this script does:
#   1. Installs fail2ban if not present
#   2. Creates /etc/fail2ban/jail.local with hardened jail configuration
#   3. Creates a custom sshd-aggressive filter for zero-tolerance SSH abuse
#   4. Creates nftables action override for Arch compatibility
#   5. Enables and restarts fail2ban
#   6. Shows jail status summary
# =============================================================================

set -euo pipefail

# --- Colors ---
readonly C_BLUE='\033[1;34m'
readonly C_RED='\033[1;31m'
readonly C_GREEN='\033[1;32m'
readonly C_YELLOW='\033[1;33m'
readonly C_NC='\033[0m'

msg()  { printf "%b[+]%b %s\n" "$C_GREEN" "$C_NC" "$1"; }
info() { printf "%b[*]%b %s\n" "$C_BLUE"  "$C_NC" "$1"; }
warn() { printf "%b[!]%b %s\n" "$C_YELLOW" "$C_NC" "$1"; }
err()  { printf "%b[!]%b %s\n" "$C_RED"   "$C_NC" "$1" >&2; exit 1; }

# --- Defaults ---
SSH_PORT=22

# --- Usage ---
usage() {
    cat <<EOF
Usage: sudo $0 [options]

Optional:
  -p PORT       SSH port (default: $SSH_PORT)
  -h            Show this help

Examples:
  sudo $0
  sudo $0 -p 2222
EOF
    exit 0
}

# --- Parse Arguments ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        -p)         SSH_PORT="$2"; shift 2 ;;
        -h|--help)  usage ;;
        *)          err "Unknown option: $1" ;;
    esac
done

# --- Validate ---
[[ $(id -u) -eq 0 ]] || err "Must be run as root"

# Validate SSH_PORT is a number in valid range
if ! [[ "$SSH_PORT" =~ ^[0-9]+$ ]] || (( SSH_PORT < 1 || SSH_PORT > 65535 )); then
    err "Invalid SSH port: $SSH_PORT (must be 1-65535)"
fi

info "SSH port: $SSH_PORT"

# =============================================================================
# 1. INSTALL FAIL2BAN
# =============================================================================

msg "Installing fail2ban..."

if pacman -Qi fail2ban &>/dev/null; then
    info "fail2ban is already installed"
else
    pacman -Syu --noconfirm --needed fail2ban
    msg "fail2ban installed successfully"
fi

# Ensure nftables is available (Arch ships it by default)
if ! command -v nft &>/dev/null; then
    warn "nftables not found, installing..."
    pacman -S --noconfirm --needed nftables
fi

# =============================================================================
# 2. CREATE JAIL CONFIGURATION
# =============================================================================

msg "Writing /etc/fail2ban/jail.local..."

# Back up existing jail.local if present
if [[ -f /etc/fail2ban/jail.local ]]; then
    BACKUP="/etc/fail2ban/jail.local.bak.$(date +%Y%m%d-%H%M%S)"
    cp /etc/fail2ban/jail.local "$BACKUP"
    info "Existing jail.local backed up to $BACKUP"
fi

cat > /etc/fail2ban/jail.local <<EOF
# =============================================================================
# fail2ban jail configuration
# Generated by AwesomeArchLinux/hardening/fail2ban/fail2ban.sh
#
# This file overrides /etc/fail2ban/jail.conf — do NOT edit jail.conf directly.
# =============================================================================

[DEFAULT]
# --- Ban defaults ---
bantime   = 1h
findtime  = 10m
maxretry  = 5

# --- nftables actions (Arch Linux default firewall) ---
banaction          = nftables-multiport
banaction_allports = nftables-allports

# --- Whitelist loopback ---
ignoreip = 127.0.0.1/8 ::1

# --- Use systemd journal (Arch does not use rsyslog by default) ---
backend = systemd

# ============================================================================
# SSH JAILS
# ============================================================================

[sshd]
enabled  = true
port     = ${SSH_PORT}
maxretry = 3
bantime  = 24h
findtime = 1h

# --- Aggressive SSH jail (custom filter) ---
# Bans on first offense for clearly malicious SSH behavior:
#   - Invalid user attempts
#   - Connections closed without authenticating
#   - Bad protocol version identification
[sshd-aggressive]
enabled  = true
filter   = sshd-aggressive
port     = ${SSH_PORT}
maxretry = 1
bantime  = 7d
findtime = 24h

# ============================================================================
# NGINX JAILS
# ============================================================================

[nginx-http-auth]
enabled  = true
port     = http,https
logpath  = /var/log/nginx/error.log
maxretry = 3
bantime  = 1h

[nginx-botsearch]
enabled  = true
port     = http,https
logpath  = /var/log/nginx/access.log
maxretry = 2
bantime  = 7d

[nginx-limit-req]
enabled  = true
port     = http,https
logpath  = /var/log/nginx/error.log
maxretry = 5
bantime  = 1h

# ============================================================================
# RECIDIVE JAIL (repeat offenders)
# ============================================================================

# Monitors fail2ban's own log. If an IP gets banned 3 times across any jail
# within 1 day, it is banned from ALL ports for 4 weeks.
[recidive]
enabled   = true
banaction = nftables-allports
logpath   = /var/log/fail2ban.log
bantime   = 4w
findtime  = 1d
maxretry  = 3
EOF

msg "jail.local written successfully"

# =============================================================================
# 3. CREATE CUSTOM SSHD-AGGRESSIVE FILTER
# =============================================================================

msg "Writing custom filter /etc/fail2ban/filter.d/sshd-aggressive.conf..."

cat > /etc/fail2ban/filter.d/sshd-aggressive.conf <<'EOF'
# =============================================================================
# fail2ban filter: sshd-aggressive
# Generated by AwesomeArchLinux/hardening/fail2ban/fail2ban.sh
#
# Zero-tolerance filter for clearly malicious SSH connection attempts.
# Designed to complement the standard [sshd] jail with a harsher ban policy.
# =============================================================================

[INCLUDES]
before = common.conf

[Definition]
_daemon = sshd

failregex = ^%(__prefix_line)sInvalid user .* from <HOST>
            ^%(__prefix_line)sConnection closed by <HOST> port \d+ \[preauth\]
            ^%(__prefix_line)sDisconnected from <HOST> port \d+ \[preauth\]
            ^%(__prefix_line)sBad protocol version identification .* from <HOST>

ignoreregex =

[Init]
journalmatch = _SYSTEMD_UNIT=sshd.service + _COMM=sshd
EOF

msg "sshd-aggressive filter created"

# =============================================================================
# 4. CREATE NFTABLES ACTION OVERRIDE
# =============================================================================

msg "Writing nftables action override /etc/fail2ban/action.d/nftables-common.local..."

mkdir -p /etc/fail2ban/action.d

cat > /etc/fail2ban/action.d/nftables-common.local <<'EOF'
# =============================================================================
# nftables action override for Arch Linux
# Generated by AwesomeArchLinux/hardening/fail2ban/fail2ban.sh
#
# Ensures fail2ban's nftables integration works with Arch's default nftables
# setup. This override sets the correct table family and chain priorities so
# fail2ban rules are evaluated before any existing accept rules.
# =============================================================================

[Init]
# Use the inet family (dual-stack IPv4/IPv6) which is Arch's default
nftables_family = inet

# Table name used by fail2ban (created automatically)
nftables_table  = f2b-table

# Chain priority — must be lower (earlier) than the default input chain
# to ensure bans take effect before other rules
nftables_chain  = input

# Set type for storing banned IPs
nftables_set_type = ipv4_addr
EOF

msg "nftables action override created"

# =============================================================================
# 5. ENABLE AND RESTART FAIL2BAN
# =============================================================================

msg "Enabling and starting fail2ban..."

systemctl enable fail2ban
systemctl restart fail2ban

# Wait briefly for jails to initialize
sleep 2

msg "fail2ban is running"

# =============================================================================
# 6. JAIL STATUS SUMMARY
# =============================================================================

echo
echo -e "${C_GREEN}========================================================================${C_NC}"
echo -e "${C_GREEN} fail2ban hardening complete!${C_NC}"
echo -e "${C_GREEN}========================================================================${C_NC}"
echo

echo -e "${C_BLUE}Configuration files:${C_NC}"
echo "  Jail config:          /etc/fail2ban/jail.local"
echo "  Aggressive filter:    /etc/fail2ban/filter.d/sshd-aggressive.conf"
echo "  nftables override:    /etc/fail2ban/action.d/nftables-common.local"
echo

echo -e "${C_BLUE}Active jails:${C_NC}"
fail2ban-client status || warn "Could not retrieve fail2ban status"
echo

echo -e "${C_BLUE}Jail overview:${C_NC}"
echo "  sshd              - Standard SSH brute-force (3 attempts -> 24h ban)"
echo "  sshd-aggressive   - Zero-tolerance SSH abuse (1 attempt -> 7d ban)"
echo "  nginx-http-auth   - HTTP basic auth failures (3 attempts -> 1h ban)"
echo "  nginx-botsearch   - Vulnerability scanner bots (2 attempts -> 7d ban)"
echo "  nginx-limit-req   - Rate limit violations (5 attempts -> 1h ban)"
echo "  recidive          - Repeat offenders (3 bans -> 4 weeks, all ports)"
echo

echo -e "${C_YELLOW}Useful commands:${C_NC}"
echo "  fail2ban-client status                  # List active jails"
echo "  fail2ban-client status sshd             # Show banned IPs for sshd"
echo "  fail2ban-client set sshd unbanip <IP>   # Unban a specific IP"
echo "  fail2ban-client reload                  # Reload configuration"
echo "  journalctl -u fail2ban -f               # Follow fail2ban logs"
echo "  nft list ruleset                        # View active nftables rules"
echo

echo -e "${C_GREEN}Done.${C_NC}"
