#!/usr/bin/env bash

# =============================================================================
# Script:      chrony.sh
# Description: Installs and configures Chrony with NTS (Network Time Security)
#              on Arch Linux for authenticated, tamper-proof time
#              synchronization.
#
# NTS (Network Time Security, RFC 8915) is the authenticated extension of
# NTP. It uses TLS 1.3 to establish trust with the time server, then
# protects each NTP packet with AEAD cookies. This prevents MITM attacks
# on time synchronization -- critical for TLS certificate validation,
# DNSSEC, Kerberos, TOTP 2FA, and log correlation.
#
# Chrony has had native NTS client support since version 4.0.
#
# Author:      Bruno Schmid @brulliant
# LinkedIn:    https://www.linkedin.com/in/schmidbruno/
#
# Usage:       sudo ./chrony.sh [-h]
#
# Requirements:
#   - Arch Linux with pacman
#   - Root privileges
#   - Internet connectivity (NTS-KE uses TCP port 4460)
#
# What this script does:
#   1. Installs chrony
#   2. Disables systemd-timesyncd (conflicts with chrony)
#   3. Backs up and writes a hardened /etc/chrony.conf with 6 NTS servers
#   4. Creates required directories and key files with strict permissions
#   5. Hardens the chronyd systemd service with a drop-in override
#   6. Enables and starts chronyd
#   7. Verifies NTS authentication is working
# =============================================================================

set -euo pipefail

# --- Colors ---
readonly C_BLUE='\033[1;34m'
readonly C_RED='\033[1;31m'
readonly C_GREEN='\033[1;32m'
readonly C_YELLOW='\033[1;33m'
readonly C_NC='\033[0m'

msg()  { printf "%b[+]%b %s\n" "$C_GREEN"  "$C_NC" "$1"; }
info() { printf "%b[*]%b %s\n" "$C_BLUE"   "$C_NC" "$1"; }
warn() { printf "%b[!]%b %s\n" "$C_YELLOW" "$C_NC" "$1"; }
err()  { printf "%b[!]%b %s\n" "$C_RED"    "$C_NC" "$1" >&2; exit 1; }

# --- Usage ---
usage() {
    cat <<EOF
Usage: sudo $0 [-h]

Options:
  -h, --help   Show this help

This script configures Chrony with NTS (Network Time Security) for
authenticated time synchronization on Arch Linux. NTS prevents
man-in-the-middle attacks on NTP traffic.

NTS servers configured:
  - time.cloudflare.com   (Cloudflare, anycast)
  - nts.netnod.se         (Netnod, Sweden)
  - ptbtime1.ptb.de       (PTB, Germany)
  - ptbtime2.ptb.de       (PTB, Germany)
  - nts.sth1.ntp.se       (Netnod Stockholm 1)
  - nts.sth2.ntp.se       (Netnod Stockholm 2)

Examples:
  sudo ./chrony.sh
EOF
    exit 0
}

# --- Parse Arguments ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)   usage ;;
        *)           err "Unknown option: $1. Use -h for help." ;;
    esac
done

# --- Validate ---
[[ $(id -u) -eq 0 ]] || err "Must be run as root"

info "Chrony NTS hardening script started"

# =============================================================================
# 1. INSTALL CHRONY
# =============================================================================

msg "Installing chrony..."

if pacman -Qi chrony &>/dev/null; then
    info "chrony is already installed"
else
    pacman -Syu --noconfirm --needed chrony
    msg "chrony installed successfully"
fi

# Verify chrony is available
if ! command -v chronyd &>/dev/null; then
    err "chronyd not found after installation. Check your installation."
fi

CHRONY_VER=$(chronyd --version 2>&1 | head -1)
info "Chrony version: $CHRONY_VER"

# =============================================================================
# 2. DISABLE systemd-timesyncd (CONFLICTS WITH CHRONY)
# =============================================================================

msg "Disabling systemd-timesyncd..."

if systemctl is-active --quiet systemd-timesyncd.service 2>/dev/null; then
    systemctl stop systemd-timesyncd.service
    info "Stopped systemd-timesyncd.service"
fi

if systemctl is-enabled --quiet systemd-timesyncd.service 2>/dev/null; then
    systemctl disable systemd-timesyncd.service
    info "Disabled systemd-timesyncd.service"
else
    info "systemd-timesyncd.service is already disabled"
fi

# =============================================================================
# 3. BACKUP AND WRITE /etc/chrony.conf
# =============================================================================

msg "Configuring /etc/chrony.conf with NTS servers..."

CHRONY_CONF="/etc/chrony.conf"

if [[ -f "$CHRONY_CONF" ]]; then
    BACKUP="${CHRONY_CONF}.bak.$(date +%Y%m%d-%H%M%S)"
    cp "$CHRONY_CONF" "$BACKUP"
    info "Backed up existing config to $BACKUP"
fi

cat > "$CHRONY_CONF" <<'EOF'
# =============================================================================
# /etc/chrony.conf — NTS-authenticated time synchronization
# Generated by AwesomeArchLinux/hardening/chrony/chrony.sh
#
# All servers below support NTS (Network Time Security, RFC 8915).
# NTS uses TLS 1.3 for the initial key exchange (NTS-KE, TCP port 4460),
# then authenticates every NTP packet with AEAD cookies.
# =============================================================================

# --- NTS Time Servers ---
# Cloudflare (anycast, global)
server time.cloudflare.com iburst nts

# Netnod (Sweden, Internet infrastructure operator)
server nts.netnod.se iburst nts

# PTB — Physikalisch-Technische Bundesanstalt (Germany, national metrology)
server ptbtime1.ptb.de iburst nts
server ptbtime2.ptb.de iburst nts

# Netnod Stockholm (Sweden, two independent servers)
server nts.sth1.ntp.se iburst nts
server nts.sth2.ntp.se iburst nts

# --- Source Validation ---
# Require at least 3 selectable sources before adjusting the clock.
# This protects against a single compromised or faulty server.
minsources 3

# --- NTS Cookie Cache ---
# Cache NTS cookies across restarts to avoid a full TLS handshake on every boot.
ntsdumpdir /var/lib/chrony

# --- Drift File ---
# Record the rate at which the system clock gains/loses time.
driftfile /var/lib/chrony/chrony.drift

# --- Clock Stepping ---
# If the clock is off by more than 1 second, step it (instant correction)
# but only during the first 3 clock updates after startup. After that,
# chrony will slew the clock gradually to avoid disrupting running services.
makestep 1.0 3

# --- Hardware Clock Sync ---
# Periodically copy the system time to the hardware (RTC) clock.
rtcsync

# --- Authentication Keys ---
keyfile /etc/chrony.keys

# --- Leap Seconds ---
# Use the right/UTC timezone data to handle leap seconds correctly.
leapsectz right/UTC

# --- Hardening: Logging ---
# Do not log client accesses (we are a client, not a server).
noclientlog

# Log directory for chrony's own logs.
logdir /var/log/chrony
log tracking measurements statistics

# --- Hardening: Access Control ---
# Only allow chronyc commands from localhost.
cmdallow 127.0.0.1
cmdallow ::1
bindcmdaddress 127.0.0.1
bindcmdaddress ::1

# --- Hardening: Client-Only Mode ---
# Disable NTP server mode — this machine is a client only.
# port 0 prevents chrony from listening on UDP port 123.
port 0
cmdport 323
EOF

chown root:root "$CHRONY_CONF"
chmod 644 "$CHRONY_CONF"
msg "NTS configuration written to $CHRONY_CONF"

# =============================================================================
# 4. CREATE CHRONY KEYS FILE
# =============================================================================

msg "Creating chrony keys file..."

CHRONY_KEYS="/etc/chrony.keys"

if [[ ! -f "$CHRONY_KEYS" ]]; then
    touch "$CHRONY_KEYS"
    info "Created $CHRONY_KEYS"
else
    info "$CHRONY_KEYS already exists"
fi

# Ensure the chrony group exists (created by the chrony package)
if getent group chrony &>/dev/null; then
    chown root:chrony "$CHRONY_KEYS"
else
    warn "Group 'chrony' does not exist. Setting owner to root:root."
    chown root:root "$CHRONY_KEYS"
fi

chmod 640 "$CHRONY_KEYS"
msg "Keys file permissions set: 640 root:chrony"

# =============================================================================
# 5. CREATE LOG DIRECTORY
# =============================================================================

msg "Creating chrony log directory..."

CHRONY_LOGDIR="/var/log/chrony"

mkdir -p "$CHRONY_LOGDIR"

if getent group chrony &>/dev/null; then
    chown root:chrony "$CHRONY_LOGDIR"
else
    chown root:root "$CHRONY_LOGDIR"
fi

chmod 750 "$CHRONY_LOGDIR"
msg "Log directory created: $CHRONY_LOGDIR (750)"

# =============================================================================
# 6. HARDEN CHRONYD SYSTEMD SERVICE
# =============================================================================

msg "Hardening chronyd systemd service..."

DROPIN_DIR="/etc/systemd/system/chronyd.service.d"
mkdir -p "$DROPIN_DIR"

cat > "$DROPIN_DIR/hardening.conf" <<'EOF'
[Service]
# --- Filesystem protection ---
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
ReadWritePaths=/var/lib/chrony /var/log/chrony /run/chrony

# --- Capabilities ---
# CAP_SYS_TIME       — adjust the system clock
# CAP_NET_BIND_SERVICE — bind to privileged NTP port (if needed)
# CAP_SETUID/SETGID  — drop privileges after startup
CapabilityBoundingSet=CAP_SYS_TIME CAP_NET_BIND_SERVICE CAP_SETUID CAP_SETGID
AmbientCapabilities=CAP_SYS_TIME CAP_NET_BIND_SERVICE

# --- Privilege escalation ---
NoNewPrivileges=yes

# --- Kernel protection ---
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectHostname=yes

# --- System call filtering ---
# @system-service — common service syscalls
# @clock          — clock_gettime, clock_settime, adjtimex, etc.
SystemCallArchitectures=native
SystemCallFilter=@system-service @clock
SystemCallErrorNumber=EPERM

# --- Network ---
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6

# --- Misc hardening ---
LockPersonality=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
RestrictNamespaces=yes
PrivateDevices=no
MemoryDenyWriteExecute=yes
EOF

systemctl daemon-reload
msg "systemd hardening applied to chronyd.service"

# =============================================================================
# 7. ENABLE AND START CHRONYD
# =============================================================================

msg "Enabling and starting chronyd..."

systemctl enable chronyd.service
systemctl restart chronyd.service

# Wait for NTS-KE handshakes to complete (TLS to 6 servers takes a moment)
info "Waiting 10 seconds for NTS key exchange with servers..."
sleep 10

if systemctl is-active --quiet chronyd.service; then
    msg "chronyd is running"
else
    warn "chronyd may not have started correctly. Check: journalctl -u chronyd"
fi

# =============================================================================
# 8. VERIFY NTS AUTHENTICATION
# =============================================================================

msg "Verifying NTS authentication..."

echo
echo -e "${C_BLUE}--- NTS Authentication Data ---${C_NC}"
echo -e "${C_BLUE}(NTS cookies should appear for each server)${C_NC}"
echo
chronyc -N authdata || warn "Could not retrieve NTS auth data"

echo
echo -e "${C_BLUE}--- Time Sources ---${C_NC}"
echo
chronyc sources -v || warn "Could not retrieve time sources"

echo
echo -e "${C_BLUE}--- NTP Data (NTS authentication status) ---${C_NC}"
echo
chronyc -N ntpdata || warn "Could not retrieve NTP data"

# =============================================================================
# 9. SUMMARY
# =============================================================================

echo
echo -e "${C_GREEN}========================================================================${C_NC}"
echo -e "${C_GREEN} Chrony NTS setup complete!${C_NC}"
echo -e "${C_GREEN}========================================================================${C_NC}"
echo

# Count NTS-authenticated sources
NTS_COUNT=0
while IFS= read -r line; do
    if [[ "$line" == *"NTS"* ]]; then
        ((NTS_COUNT++)) || true
    fi
done < <(chronyc -N authdata 2>/dev/null || true)

echo -e "${C_BLUE}NTS Status:${C_NC}"
if [[ "$NTS_COUNT" -gt 0 ]]; then
    echo -e "  ${C_GREEN}$NTS_COUNT server(s) authenticated with NTS${C_NC}"
else
    echo -e "  ${C_YELLOW}NTS cookies not yet established.${C_NC}"
    echo "  This can take a minute. Re-check with: chronyc -N authdata"
fi
echo

echo -e "${C_BLUE}NTS servers configured:${C_NC}"
echo "  - time.cloudflare.com   (Cloudflare, anycast)"
echo "  - nts.netnod.se         (Netnod, Sweden)"
echo "  - ptbtime1.ptb.de       (PTB, Germany)"
echo "  - ptbtime2.ptb.de       (PTB, Germany)"
echo "  - nts.sth1.ntp.se       (Netnod Stockholm 1)"
echo "  - nts.sth2.ntp.se       (Netnod Stockholm 2)"
echo

echo -e "${C_BLUE}Configuration files:${C_NC}"
echo "  Chrony config:    /etc/chrony.conf"
echo "  Keys file:        /etc/chrony.keys"
echo "  Log directory:    /var/log/chrony/"
echo "  NTS cookie cache: /var/lib/chrony/"
echo "  systemd drop-in:  $DROPIN_DIR/hardening.conf"
echo

echo -e "${C_BLUE}Verification commands:${C_NC}"
echo "  chronyc -N authdata     # Show NTS cookie status per server"
echo "  chronyc sources -v      # Show time sources and status"
echo "  chronyc -N ntpdata      # Show NTS authentication details"
echo "  chronyc tracking        # Show current clock tracking info"
echo "  chronyc serverstats     # Show server request statistics"
echo "  systemctl status chronyd  # Check service status"
echo

echo -e "${C_YELLOW}IMPORTANT: Firewall requirements${C_NC}"
echo "  NTS-KE (Key Establishment) uses TCP port 4460 outbound."
echo "  Standard NTP uses UDP port 123 outbound."
echo "  Ensure your firewall allows these outbound connections:"
echo "    - TCP 4460 (outbound) — NTS-KE TLS handshake"
echo "    - UDP 123  (outbound) — NTP time queries"
echo

echo -e "${C_GREEN}Done.${C_NC}"
