#!/usr/bin/env bash

# =============================================================================
# Script:      ssh.sh
# Description: Hardens OpenSSH server and client configuration on Arch Linux.
#              Regenerates host keys (Ed25519 + RSA 4096), enforces modern
#              cryptographic algorithms, restricts access, and applies
#              CIS Benchmark recommendations for SSH.
#
# Author:      Bruno Schmid @brulliant
# LinkedIn:    https://www.linkedin.com/in/schmidbruno/
#
# Usage:       sudo ./ssh.sh [-u ALLOWED_USER] [-p PORT] [-h]
#
# =============================================================================

set -euo pipefail

BBlue='\033[1;34m'
BRed='\033[1;31m'
BGreen='\033[1;32m'
BYellow='\033[1;33m'
NC='\033[0m'

SSH_PORT=22
REVOKED_KEYS_FILE='/etc/ssh/revokedKeys'

# --- Parse Arguments ---
show_help() {
    echo "Usage: sudo $0 [-u ALLOWED_USER] [-p PORT] [-h]"
    echo "  -u USER   User to allow SSH access (required, must not be root)"
    echo "  -p PORT   SSH listening port (default: 22)"
    echo "  -h        Show this help"
    exit 0
}

ALLOWED_USERS=""
while getopts ":u:p:h" opt; do
    case "$opt" in
        u) ALLOWED_USERS="$OPTARG" ;;
        p) SSH_PORT="$OPTARG" ;;
        h) show_help ;;
        *) show_help ;;
    esac
done

# Check if the user is root
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

# Resolve ALLOWED_USERS: flag > SUDO_USER > prompt
if [ -z "$ALLOWED_USERS" ]; then
    ALLOWED_USERS="${SUDO_USER:-}"
fi
if [ -z "$ALLOWED_USERS" ] || [ "$ALLOWED_USERS" = "root" ]; then
    echo -e "${BRed}ERROR: ALLOWED_USERS must be a non-root user.${NC}" >&2
    echo "Specify with: sudo $0 -u <username>" >&2
    echo "Or run via: sudo -u root ./ssh.sh (SUDO_USER will be detected)" >&2
    exit 1
fi
echo -e "${BGreen}SSH access will be granted to: ${ALLOWED_USERS}${NC}"

echo -e "${BBlue}Cleaning old keys...${NC}"
if [ ! -d /etc/ssh ]; then
    echo -e "${BRed}ERROR: /etc/ssh does not exist. Is openssh installed?${NC}" >&2
    exit 1
fi
shred -u /etc/ssh/ssh_host_*key* 2>/dev/null || true

echo -e "${BBlue}Creating ed25519 and RSA keys...${NC}"
ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" < /dev/null
ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N "" < /dev/null

# Set correct permissions on host keys
chmod 600 /etc/ssh/ssh_host_ed25519_key /etc/ssh/ssh_host_rsa_key
chmod 644 /etc/ssh/ssh_host_ed25519_key.pub /etc/ssh/ssh_host_rsa_key.pub
chown root:root /etc/ssh/ssh_host_*

echo -e "${BBlue}Hardening \"/etc/ssh/sshd_config\"...${NC}"

# Back up original config
BACKUP_SUFFIX="bak.$(date +%Y%m%d%H%M%S)"
cp /etc/ssh/sshd_config "/etc/ssh/sshd_config.${BACKUP_SUFFIX}"

touch "$REVOKED_KEYS_FILE"

# Write a complete hardened sshd_config (truncate, not append — avoids first-match-wins issues)
cat > /etc/ssh/sshd_config << SSHD_EOF
# =============================================================================
# Hardened sshd_config — generated by ssh.sh
# Original backed up to: /etc/ssh/sshd_config.${BACKUP_SUFFIX}
# =============================================================================

# --- Network ---
Port ${SSH_PORT}
AddressFamily inet
StrictModes yes

# --- Host Keys ---
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key

# --- Cryptographic Algorithms (OpenSSH 9.x+ modern) ---
HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256
KexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com

# --- Key Types ---
CASignatureAlgorithms ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519
HostbasedAcceptedAlgorithms ssh-ed25519,rsa-sha2-512,rsa-sha2-256
PubkeyAcceptedAlgorithms sk-ssh-ed25519@openssh.com,ssh-ed25519,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256

# --- Authentication ---
AuthenticationMethods publickey
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PasswordAuthentication no
PermitEmptyPasswords no
KbdInteractiveAuthentication no
KerberosAuthentication no
GSSAPIAuthentication no
HostbasedAuthentication no
IgnoreRhosts yes
PermitUserEnvironment no
UsePAM yes

# --- Access Control ---
PermitRootLogin no
AllowUsers ${ALLOWED_USERS}
MaxAuthTries 3
MaxSessions 2
MaxStartups 10:30:60
LoginGraceTime 60

# --- Forwarding (all disabled) ---
DisableForwarding yes

# --- Session ---
X11Forwarding no
Banner /etc/issue.net
PrintLastLog yes
RekeyLimit 512M 1h
ClientAliveInterval 300
ClientAliveCountMax 0
TCPKeepAlive no
Compression no
PermitUserRC no
VersionAddendum none

# --- Logging ---
LogLevel VERBOSE
SyslogFacility AUTH
UseDNS no

# --- Revoked Keys ---
RevokedKeys ${REVOKED_KEYS_FILE}

# --- Subsystem ---
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/ssh/sftp-server -f AUTHPRIV -l INFO
SSHD_EOF

echo -e "${BBlue}Hardening \"/etc/ssh/ssh_config\"...${NC}"
cp /etc/ssh/ssh_config "/etc/ssh/ssh_config.${BACKUP_SUFFIX}" 2>/dev/null || true

cat > /etc/ssh/ssh_config << 'SSH_CLIENT_EOF'
# Hardened ssh_config — generated by ssh.sh

HashKnownHosts yes

Host *
    ConnectTimeout 30
    ServerAliveInterval 10
    HostKeyAlgorithms ssh-ed25519,rsa-sha2-512,rsa-sha2-256
    KexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512
    Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
    MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
    StrictHostKeyChecking accept-new
    UpdateHostKeys ask
    ControlMaster auto
    ControlPersist 10m
    ControlPath ~/.ssh/sockets/%r@%h:%p
SSH_CLIENT_EOF

echo -e "${BBlue}Hardening permissions...${NC}"
chown root:root /etc/ssh/sshd_config
chmod 600 /etc/ssh/sshd_config

echo -e "${BBlue}Creating Banner (/etc/issue.net).${NC}"

cat > /etc/issue.net << EOF
                     .ed"""" """\$\$\$\$be.
                   -"           ^""**\$\$\$e.
                 ."                   '\$\$\$c
                /                      "4\$\$b
               d  3                     \$\$\$\$
               \$  *                   .\$\$\$\$\$\$
              .\$  ^c           \$\$\$\$\$e\$\$\$\$\$\$\$\$.
              d\$L  4.         4\$\$\$\$\$\$\$\$\$\$\$\$\$\$b
              \$\$\$\$b ^ceeeee.  4\$\$ECL.F*\$\$\$\$\$\$\$
  e\$""=.      \$\$\$\$P d\$\$\$\$F \$ \$\$\$\$\$\$\$\$\$- \$\$\$\$\$\$
 z\$\$b. ^c     3\$\$\$F "\$\$\$\$b   \$"\$\$\$\$\$\$\$  \$\$\$\$*"      .=""\$c
4\$\$\$\$L   \     \$\$P"  "\$\$b   .\$ \$\$\$\$\$...e\$\$        .=  e\$\$\$.
^*\$\$\$\$\$c  %..   *c    ..    \$\$ 3\$\$\$\$\$\$\$\$\$\$eF     zP  d\$\$\$\$\$
  "**\$\$\$ec   "\   %ce""    \$\$\$  \$\$\$\$\$\$\$\$\$\$*    .r" =\$\$\$\$P""
        "*\$b.  "c  *\$e.    *** d\$\$\$\$\$"L\$\$    .d"  e\$\$***"
          ^*\$\$c ^\$c \$\$\$      4J\$\$\$\$\$% \$\$\$ .e*".eeP"
             "\$\$\$\$\$\$"'\$=e....\$*\$\$**\$cz\$\$" "..d\$*"
               "*\$\$\$  *=%4.\$ L L\$ P3\$\$\$F \$\$\$P"
                  "\$   "%*ebJLzb\$e\$\$\$\$\$b \$P"
                    %..      4\$\$\$\$\$\$\$\$\$\$ "
                     \$\$\$e   z\$\$\$\$\$\$\$\$\$\$%
                      "*\$c  "\$\$\$\$\$\$\$P"
                       ."""*\$\$\$\$\$\$\$\$bc
                    .-"    .\$***\$\$\$"""*e.
                 .-"    .e\$"     "*\$c  ^*b.
          .=*""""    .e\$*"          "*bc  "*\$e..
        .\$"        .z*"               ^*\$e.   "*****e.
        \$\$ee\$c   .d"                     "*\$.        3.
        ^*\$E")\$..\$"                         *   .ee==d%
           \$.d\$\$\$*                           *  J\$\$\$e*
            """""                             "\$\$\$"

********************************************************************
*                                                                  *
* This system is for the use of authorized users only. Usage of    *
* this system may be monitored and recorded by system personnel.   *
*                                                                  *
* Anyone using this system expressly consents to such monitoring   *
* and is advised that if such monitoring reveals possible          *
* evidence of criminal activity, system personnel may provide the  *
* evidence from such monitoring to law enforcement officials.      *
*                                                                  *
********************************************************************
EOF

chown root:root /etc/issue.net
chmod 644 /etc/issue.net

# Validate sshd configuration before restarting
echo -e "${BBlue}Validating sshd configuration...${NC}"
if sshd -t; then
    echo -e "${BGreen}Configuration valid.${NC}"
    echo -e "${BBlue}Enabling and restarting SSHD...${NC}"
    systemctl enable sshd.service
    systemctl restart sshd.service
    systemctl status sshd.service --no-pager
else
    echo -e "${BRed}ERROR: sshd_config validation failed! NOT restarting.${NC}" >&2
    echo -e "${BYellow}Rolling back to previous configuration...${NC}"
    cp "/etc/ssh/sshd_config.${BACKUP_SUFFIX}" /etc/ssh/sshd_config
    echo "Review /etc/ssh/sshd_config and fix errors before restarting manually." >&2
    exit 1
fi

# Rate limiting with iptables
echo -e "${BBlue}Rate Limiting with iptables to avoid brute-forcing...${NC}"
if ! iptables -C INPUT -p tcp --dport "$SSH_PORT" -m conntrack --ctstate NEW -m recent --set 2>/dev/null; then
    iptables -A INPUT -p tcp --dport "$SSH_PORT" -m conntrack --ctstate NEW -m recent --set
    iptables -A INPUT -p tcp --dport "$SSH_PORT" -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 4 -j DROP
fi

# Persist iptables rules
if command -v iptables-save &>/dev/null; then
    mkdir -p /etc/iptables
    iptables-save > /etc/iptables/iptables.rules
    systemctl enable iptables.service 2>/dev/null || true
fi

echo -e "${BGreen}SSH hardening complete. Running on port ${SSH_PORT}.${NC}"
echo -e "${BBlue}Allowed user: ${ALLOWED_USERS}${NC}"
echo -e "${BYellow}IMPORTANT: Ensure ${ALLOWED_USERS} has an SSH key in ~/.ssh/authorized_keys${NC}"
echo -e "${BYellow}before disconnecting, as password authentication is now disabled.${NC}"
