#!/usr/bin/env bash

# =============================================================================
# Script:      nano.sh
# Description: Installs nano with syntax highlighting and applies hardened
#              editor settings (backup, locking, secure permissions).
#
# Author:      Bruno Schmid @brulliant
# LinkedIn:    https://www.linkedin.com/in/schmidbruno/
#
# Usage:       ./nano.sh
# =============================================================================

set -euo pipefail

BBlue='\033[1;34m'
BRed='\033[1;31m'
BGreen='\033[1;32m'
NC='\033[0m'

# Must NOT run as root — config goes into user home
if [ "$(id -u)" -eq 0 ]; then
    echo -e "${BRed}Do not run this script as root. Run as your normal user.${NC}" >&2
    exit 1
fi

# Install nano if not already installed
if ! command -v nano &>/dev/null; then
    echo -e "${BBlue}Installing nano...${NC}"
    sudo pacman -S --noconfirm nano
fi

# Install syntax highlighting from the Arch package (safer than curl | sh)
echo -e "${BBlue}Installing nano syntax highlighting...${NC}"
sudo pacman -S --noconfirm nano-syntax-highlighting 2>/dev/null || true

# Create backup directory
mkdir -p "$HOME/.cache/nano/backups"

NANORC="$HOME/.nanorc"

# Write a complete config (idempotent — overwrites any previous version)
echo -e "${BBlue}Writing nano configuration...${NC}"
cat > "$NANORC" << 'EOF'
# Nano configuration — generated by nano.sh

# Backup settings
set backup
set backupdir "~/.cache/nano/backups/"

# Editor behavior
set constantshow
set locking
set nohelp
set nonewlines
set nowrap
set minibar
set zap
set linenumbers
set tabsize 4
set tabstospaces

# Syntax highlighting (Arch package)
include "/usr/share/nano-syntax-highlighting/*.nanorc"
EOF

# Set secure permissions (no sudo needed — user file)
chmod 600 "$NANORC"

echo -e "${BGreen}Nano configuration completed successfully.${NC}"
