# User's picom configuration.
# Vendored from https://github.com/owl4ce/dotfiles (GPL-3.0).

# SHADOWS
shadow = true;
shadow-radius = 40;
shadow-opacity = 0.1;
shadow-offset-x = -27;
shadow-offset-y = -27;
shadow-exclude = [
    "class_g             = 'Conky'",
    "class_g             = 'GLava'",
    "class_g            ?= 'Notify-osd'",
    "class_g             = 'Tint2'",
    "window_type         = 'dock'",
    "window_type         = 'desktop'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "_GTK_FRAME_EXTENTS@:c"
];
xinerama-shadow-crop = true;

# FADING
fading = true;
fade-in-step = 0.025;
fade-out-step = 0.025;
fade-delta = 4;
no-fading-destroyed-argb = true;

# OPACITY
inactive-opacity-override = false;
frame-opacity = 0.92;
opacity-rule = [
    "92:class_g = 'Terminator' && focused",
    "82:class_g = 'Terminator' && !focused",
    "96:class_g = 'Rofi'",
    "90:class_g = 'Dunst'"
];

# CORNERS
corner-radius = 8;
rounded-corners-exclude = [
    "name               *= 'rofi'",
    "name               *= 'screenkey'",
    "name               *= 'tint2'",
    "class_g             = 'Conky'",
    "class_g             = 'GLava'",
    "window_type         = 'dock'",
    "window_type         = 'desktop'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "_GTK_FRAME_EXTENTS@:c"
];

# BACKGROUND BLURRING
blur-method = "none";
blur-background-exclude = [
    "! name             ~= ''",
    "  name             *= 'jgmenu'",
    "  name             *= 'tint2'",
    "class_g             = 'Conky'",
    "class_g             = 'GLava'",
    "window_type         = 'dock'",
    "window_type         = 'desktop'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "_GTK_FRAME_EXTENTS@:c"
];

# GENERAL
backend = "glx";
vsync = true;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-ewmh-active-win = true;
unredir-if-possible = false;
detect-transient = true;
detect-client-leader = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
xrender-sync-fence = true;
log-level = "warn";
log-file = "/dev/null";

wintypes:
{
    tooltip       = { fade = true; shadow = true;  opacity           = 1.00; };
    menu          = { fade = true; shadow = true;  opacity           = 1.00; };
    popup_menu    = { fade = true; shadow = true;  opacity           = 1.00; };
    dropdown_menu = { fade = true; shadow = true;  opacity           = 1.00; };
    utility       = { fade = true; shadow = true;  opacity           = 1.00; };
    dialog        = { fade = true; shadow = true;  opacity           = 1.00; };
    notify        = { fade = true; shadow = true;  opacity           = 1.00; };
    dock          = { fade = true; shadow = false; clip-shadow-above = true; };
    dnd           = { fade = true; shadow = false;                           };
    unknown       = { fade = true; shadow = true;  opacity           = 1.00; };
};
